export const ADD_DOC = 'ADD_DOC'
export const DELETE_DOC = 'DELETE_DOC'

export const CHANGE_INSURANCE_NUMBER = 'CHANGE_INSURANCE_NUMBER'
export const CHANGE_GENDER = 'CHANGE_GENDER'
export const CHANGE_NAME = 'CHANGE_NAME'
export const CHANGE_SURNAME = 'CHANGE_SURNAME'
